Let the doctest pass with Python 2.7.2 by using +ELLLISIS.
In Python 2.7.5, subscripting the None object raises TypeError with
the following message::

  >>> None[:]
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  TypeError: 'NoneType' object has no attribute '__getitem__'

But in Python 2.7.2, we got::

  >>> None[:]
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  TypeError: 'NoneType' object is not subscriptable

Therefore, we need to ask doctest to ignore the different texts in the
error message, to get the test pass in both version.